collections: 
  - amazon.aws
  - awx.awx
  - community.aws
  - community.crypto
  - community.docker
  - community.general
  - community.google
  - community.grafana
  - community.hashi_vault
  - community.libvirt
  - community.mysql
  - community.network
  - community.zabbix
  - containers.podman
  - google.cloud
  - hetzner.hcloud

# Disabled due to issue with azure_compute #
  # - community.azure 
  # - chocolatey.chocolatey 
  # - azure.azcollection # Disabled due to issue with azure_compute #
  # - netapp.um_info # Disabled due to issue with azure_compute
  # - netapp.azure # Disabled due to issue with azure_compute
  
# Seems to break things in spectacular fashion 
  # - infinidat.infinibox 
